Added 404 page
R2Northstar/NorthstarTF pull request #13
Opened 2022-12-07 09:27 UTC by taskinoz

Taken from the old master server.

@pg9182 you'll need to add an entry in nginx or atlas to use this page as a 404.

2022-12-08 00:56 UTC, pg9182 requested changes
~~Can you rename it to `.errors/404.html`?~~

Edit: Nevermind, I'm going to support error pages in the root directory since it's what GitHub Pages supports, and we're eventually going to be using it.

2022-12-12 04:40 UTC, pg9182 requested changes
Can you move the error page to `404.html` in the root dir?

2022-12-13 16:41 UTC, pg9182 requested changes

2022-12-23 04:09 UTC, taskinoz commented on dist/404.html
> +            <source src="assets/NorthstarPromoVid.mp4">
What do you mean by this

2022-12-23 04:09 UTC, taskinoz commented on dist/404.html
> +</html>
Added

2022-12-23 04:09 UTC, taskinoz commented on dist/style/404.css
> +}
Added

2022-12-23 04:09 UTC, taskinoz commented on dist/style/404.css
> +    */
Removed

2023-03-02 03:30 UTC, pg9182 commented on dist/404.html
> +        <video class="lazy" autoplay loop muted playsinline poster="assets/NorthstarPromoPoster.jpg">
This too.

2023-03-02 03:34 UTC, taskinoz commented on dist/404.html
> +        <video class="lazy" autoplay loop muted playsinline poster="assets/NorthstarPromoPoster.jpg">
Updated

2023-03-02 03:39 UTC, pg9182 approved these changes
LGTM

2023-03-02 03:39 UTC, merged